### ISSUE TITLE
Debugger easily locks up the entire session

### ISSUE THREAD

**Issue by StevenLooman** [OpenSmallworld/magik-debugger#6] opened 2020-12-21 19:40 UTC
First of all, awesome that there is debugger support in SW5!

It is, however, very easy to lock the entire session. For example, when paused at a breakpoint, adding a new breakpoint locks the session (or at least the CLI.) Running tests using munit often causes a locked session as well.

Using SW525, having the same problems on both Windows and Linux.

**Comment by StevenLooman** [comment] 2020-12-21 20:53
Is there any way I can look into this myself? I would be happy to help. The problem does not seem to be with magik-debugger however, but rather in the mda and/or Smallworld itself.

**Comment by paulwarwicker** [comment] 2020-12-23 14:34
Thanks for the comment. 

First of all, the browser interface version was a bit rough and ready and is very unlikely to be updated, ever. Secondly, it is not possible to share any of the code for mda or the interface to Smallworld as this is proprietary. Sorry.

Are you using the browser interface? You may find that using the [magik-vscode](https://github.com/OpenSmallworld/magik-vscode) plugin for vscode, has more success. Although the API to mda has not changed at all since the initial release, the wrapper around it from vscode is somewhat different. That said, it is still possible for lock-ups to occur using vscode, and the [README.md](https://github.com/OpenSmallworld/magik-vscode/blob/master/README.md) mentions this.

We know that the situation of pausing at a breakpoint and then setting another breakpoint definitely would work as that is a common use case which we use all the time.

Interesting that you mention causing a lock-up using munit. If you can isolate that and provide a standalone example, we can definitely look into that, even though this is made available as Class C (unsupported) code.

-paul

**Comment by paulwarwicker** [comment] 2020-12-24 14:52
**UPDATE**: We have found that the problem is possibly tied to a change in Java 15. Which Java version are you using?

We have not fully analysed the issue yet, so we do not know what might be involved to fix it. The obvious workaround is to use an LTS version of  Java 11. This is the reason several of us have not encountered the problem.

-paul

**Comment by StevenLooman** [comment] 2020-12-27 20:22
Apologies for my delayed response and thank you for your quick response. Running on Java 11 does seem to fix the problem. I am using the browser interface, which does seem to work fine now.

Just wondering, is there any documentation around the mda? I cannot find any information about it in the documents. Mostly wondering if there are supported features not available in the browser interface and/or the magik-vscode plugin.

**Comment by paulwarwicker** [comment] 2021-01-04 20:01
There is no documentation available. Sorry.

mda implements only what is required, therefore everything that is implemented is used. There is no hidden or withheld functionality.

The good news is that we have identified a potential fix which will be addressed initially in 527. Given the nature of the API, this will almost certainly work at earlier versions.

-paul

**Comment by StevenLooman** [comment] 2021-01-04 21:02
Great to hear a fix will be address in 527!

Closing this issue.

**Comment by paulwarwicker** [comment] 2021-01-18 16:16
We have fixed this at 5.2.7. I have just uploaded them to the lib directory. 
Download the new file, rename the existing mda.dll and then rename the later version in its place.

-paul

**Closed** 2021-01-22 13:17 UTC

**Comment by StevenLooman** [comment] 2021-01-22 16:42
I was able to (lightly) test it on Windows today and I haven't seen any lock ups. Thank you!
